import assert from 'node:assert/strict';
const base='http://127.0.0.1:8787';
let r=await fetch(base+'/api/contracts');assert.equal(r.status,401);
r=await fetch(base+'/');assert.match(await r.text(),/Sign in/);
r=await fetch(base+'/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'password=wrong',redirect:'manual'});assert.equal(r.status,401);
r=await fetch(base+'/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'password=local-test-password-only',redirect:'manual'});assert.equal(r.status,303);const cookie=r.headers.get('set-cookie').split(';')[0];
const headers={Cookie:cookie};
const pages=[{file:'synthetic-test.pdf',page:1,text:'SYNTHETIC TEST CONTRACT\nCustomer name: Test Customer\nVIN: 1HGCM82633A004352\nCovered components: water pump, alternator.\nExclusions: wear items and brake pads.\nPrior authorization required.'}];
const data={customer:'Test Customer',vin:'1HGCM82633A004352',company:'Example Warranty',claimsPhone:'800-555-0100',vehicle:'2003 Honda Accord'};
const form=new FormData();form.set('data',JSON.stringify(data));form.set('pages',JSON.stringify(pages));form.append('files',new Blob(['%PDF-1.4\nSynthetic file for storage testing only'],{type:'application/pdf'}),'synthetic-test.pdf');
r=await fetch(base+'/api/contracts',{method:'POST',headers,body:form});assert.equal(r.status,201,await r.clone().text());const {id}=await r.json();
r=await fetch(base+'/api/contracts/'+id,{headers});assert.equal(r.status,200);let record=await r.json();assert.equal(record.vin,data.vin);assert.equal(record.pages[0].text,pages[0].text);assert.equal(record.files.length,1);
r=await fetch(base+'/api/contracts/'+id+'/file',{headers});assert.equal(r.status,200);assert.match(await r.text(),/%PDF/);
r=await fetch(base+'/api/contracts/'+id,{method:'PATCH',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({...data,customer:'Updated Test Customer'})});assert.equal(r.status,200);
r=await fetch(base+'/api/contracts/'+id,{headers});record=await r.json();assert.equal(record.customer,'Updated Test Customer');
r=await fetch(base+'/api/contracts',{headers});assert.ok((await r.json()).records.some(x=>x.id===id));
r=await fetch(base+'/api/contracts',{method:'POST',headers:{...headers,Origin:'https://wrong.example'},body:form});assert.equal(r.status,403);
r=await fetch(base+'/api/analyze',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({pages})});assert.equal(r.status,502);assert.match((await r.json()).error,/not configured/);
r=await fetch(base+'/api/config',{headers});assert.equal((await r.json()).ai,false);
r=await fetch(base+'/api/contracts/'+id+'/file');assert.equal(r.status,401);
console.log('PASS: login, unauthorized API and file access, D1 create/read/update/list, R2 file round-trip, cross-origin rejection, AI-not-configured fallback.');
