export type Page={file:string,page:number,text:string};
export const fields=[['customer','Customer name'],['vin','VIN'],['vehicle','Year / make / model'],['company','Warranty company'],['administrator','Claims administrator'],['contractNumber','Contract number'],['plan','Coverage plan'],['coverageType','Contract type'],['claimsPhone','Claims phone number'],['claimNumber','Existing claim number'],['paymentEmail','Invoice submission email'],['paymentPortal','Invoice / claims portal'],['deductible','Deductible'],['expiration','Expiration date'],['mileage','Expiration mileage']] as const;
export type Details=Record<string,string>;
export function extract(pages:Page[]):Details{
 const text=pages.map(p=>p.text).join('\n');
 const get=(label:string)=>text.match(new RegExp('(?:^|\\n)\\s*(?:'+label+')\\s*[:#]\\s*([^\\n]+)','i'))?.[1]?.trim()||'';
 return {coverageType:'',customer:get('customer(?: name)?|contract holder|purchaser(?: name)?|owner(?: name)?'),vin:text.match(/\b[A-HJ-NPR-Z0-9]{17}\b/i)?.[0]?.toUpperCase()||'',vehicle:get('vehicle|year[/ ]make[/ ]model'),company:get('warranty company|provider|obligor'),administrator:get('(?:claims? )?administrator|administered by'),contractNumber:get('contract(?: number| no\\.?| #)?|agreement number'),plan:get('coverage plan|plan|coverage level'),claimsPhone:(text.match(/(?:claims?(?:\s+(?:phone|department|number|service))?|prior authorization)[^\n\d]{0,40}((?:\+?1[ .-]?)?\(?\d{3}\)?[ .-]?\d{3}[ .-]?\d{4})/i)?.[1]||''),claimNumber:get('claim number|claim #'),paymentEmail:(text.match(/(?:invoice|payment|submit)[^\n]{0,100}?([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})/i)?.[1]||''),paymentPortal:get('claims portal|payment portal|invoice portal'),deductible:get('deductible'),expiration:get('expiration date|expires'),mileage:get('expiration mileage|mileage limit')};
}
const aliases:Record<string,string[]>={'water pump':['water pump','coolant pump'],'alternator':['alternator','generator'],'ac compressor':['a/c compressor','air conditioning compressor','ac compressor'],'transmission':['transmission','transaxle']};
export function searchCoverage(pages:Page[],query:string){const q=query.trim().toLowerCase();if(q.length<2)return [];const terms=aliases[q]||[q];return pages.flatMap(p=>{const lower=p.text.toLowerCase();const ranges:{start:number,end:number}[]=[];for(const term of terms){let from=0;while(from<lower.length){const at=lower.indexOf(term,from);if(at<0)break;from=at+term.length;if(/[a-z0-9]/i.test(lower[at-1]||'')||/[a-z0-9]/i.test(lower[at+term.length]||''))continue;const start=Math.max(0,at-320),end=Math.min(p.text.length,at+term.length+450);if(!ranges.some(r=>start<=r.end&&end>=r.start))ranges.push({start,end});}}return ranges.map(r=>({file:p.file,page:p.page,text:p.text.slice(r.start,r.end)}));});}
